apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-creator-sa
  namespace: dpyravlos
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: dpyravlos
  name: job-creator
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch", "delete", "deletecollection", "patch", "update"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: job-creator-binding
  namespace: dpyravlos
subjects:
- kind: ServiceAccount
  name: job-creator-sa
  namespace: dpyravlos
roleRef:
  kind: Role
  name: job-creator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: manager-pv
  namespace: dpyravlos
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keep-alive-pod-pvc
  namespace: dpyravlos
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: manager
  namespace: dpyravlos
  labels:
    app: managers
spec:
  ports:
    - port: 5000
      name: manager
      protocol: TCP
  clusterIP: None
  selector:
    app: managers
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: manager
  namespace: dpyravlos
spec:
  serviceName: "managers"
  replicas: 2
  selector:
    matchLabels:
      app: managers
  template:
    metadata:
      labels:
        app: managers
    spec:
      serviceAccountName: job-creator-sa  # Service account added here
      containers:
        - name: mapreduce
          image: kyri56xcaesar/katanemimena:manager
          command: ["python3"]
          args: ["/manager.py"]
          ports:
            - containerPort: 5000
              name: manager
          volumeMounts:
            - mountPath: "/mnt/data/"
              name: manager-storage
      volumes:
      - name: manager-storage
        persistentVolumeClaim:
          claimName: keep-alive-pod-pvc
