kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: endpoints-reader
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: endpoints-reader-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: dpyravlos
roleRef:
  kind: ClusterRole
  name: endpoints-reader
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dpyravlos
  name: service-reader
rules:
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-reader-binding
  namespace: dpyravlos
subjects:
- kind: ServiceAccount
  name: dpyravlos # replace this if your pods use a different service account
  namespace: dpyravlos
roleRef:
  kind: Role
  name: service-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: uiservice
  namespace: dpyravlos
spec:
  type: NodePort
  selector:
    app: uiservice
  ports:
    - protocol: TCP
      port: 1338 # External port you want to expose (can be any available port)
      targetPort: 1338  # Port on which your service is running within the pod
      nodePort: 30002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uiservice
  namespace: dpyravlos
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: uiservice
  template:
    metadata:
      labels:
        app: uiservice
    spec:
      containers:
      - name: uiservice
        image: kyri56xcaesar/katanemimena:uiservice  # Replace with your actual image and tag
        ports:
          - containerPort: 1338  # Port your application listens on inside the container
        resources:
          requests:
            cpu: "0.1"  # Request 0.1 CPU cores
            memory: "100Mi"  # Request 100 MiB memory
          limits:
            cpu: "0.5"  # Limit to 0.5 CPU cores
            memory: "500Mi"  # Limit to 500 MiB memory
---
apiVersion: v1
kind: Service
metadata:
  name: authservice
  namespace: dpyravlos
spec:
  type: NodePort
  selector:
    app: authservice
  ports:
    - protocol: TCP
      port: 1337  # External port you want to expose
      targetPort: 1337  # Port on which authservice is running within the pod
      nodePort: 30003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice
  namespace: dpyravlos
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
      - name: authservice
        image: kyri56xcaesar/katanemimena:authservice  # Use the image tag you built
        ports:
        - containerPort: 1337  # Ensure this matches the exposed port in your Dockerfile
        resources:
          requests:
            cpu: "0.1"  # Request 0.1 CPU cores
            memory: "100Mi"  # Request 100 MiB memory
          limits:
            cpu: "0.5"  # Limit to 0.5 CPU cores
            memory: "500Mi"  # Limit to 500 MiB memory


