apiVersion: v1
kind: Service
metadata:
  name: manager
  labels:
    app: managers
spec:
  ports:
    - port: 8070
      name: manager
  clusterIP: None
  selector:
    app: managers
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: manager
spec:
  serviceName: "managers"
  replicas: 1
  selector:
    matchLabels:
      app: managers
  template:
    metadata:
      labels:
        app: managers
    spec:
      containers:
        - name: mapreduce
          imagePullPolicy: IfNotPresent
          image: manager:latest
          command: ["python3"]
          args: ["/shuffler.py", "-i", "/mnt/data/shuffler/in/mapper.out", "-o", "/mnt/data/reducer/in/shuffler.out"]
          ports:
            - containerPort: 8081
              name: shuffler
          volumeMounts:
            - mountPath: "/mnt/data/"
              name: mapper-storage
      volumes:
      - name: mapper-storage
        persistentVolumeClaim:
          claimName: keep-alive-pod-pvc
