apiVersion: v1
kind: Service
metadata:
  name: mappers
  labels:
    app: mappers
spec:
  ports:
    - port: 8080
      name: mapper
  clusterIP: None
  selector:
    app: mappers
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mapper
spec:
  serviceName: "mappers"
  replicas: 1
  selector:
    matchLabels:
      app: mappers
  template:
    metadata:
      labels:
        app: mappers
    spec:
      containers:
        - name: mapreduce
          imagePullPolicy: IfNotPresent
          image: mapper:latest
          command: ["sh", "-c", "cp /mnt/data/mapper_input.py /mapper_input.py && python3 /mapper_skeleton.py -i /mnt/data/mapper/in/mapper.in -o /mnt/data/shuffler/in/mapper.out"]
          #command: ["python3"]
          #args: ["/mapper_skeleton.py", "-i", "/mnt/data/mapper/in/mapper.in", "-o", "/mnt/data/shuffler/in/mapper.out"]
          ports:
            - containerPort: 8080
              name: mapper
          volumeMounts:
            - mountPath: "/mnt/data/"
              name: mapper-storage
      volumes:
      - name: mapper-storage
        persistentVolumeClaim:
          claimName: keep-alive-pod-pvc
