apiVersion: batch/v1
kind: Job
metadata:
  name: reducer-job
spec:
  completions: 1
  parallelism: 1
  completionMode: Indexed
  template:
    metadata:
      labels:  # Fixed typo here
        app: reducers
    spec:
      containers:
        - name: mapreduce
          image: reducer:latest
          imagePullPolicy: IfNotPresent
          command:
            [
              "sh", "-c",
              'echo "${MYFUNC}" > /reducer_input.py && python3 /reducer_skeleton.py -i /mnt/data/reducer/in/mapper-${JOB_INDEX}.out -o /mnt/data/reducer/out/reducer-${JOB_INDEX}.out'
            ]
          ports:
          - containerPort: 8081
            name: reducer
          volumeMounts:
          - mountPath: "/mnt/data/"
            name: reducer-storage  # Fixed name here
          env:
          - name: JOB_INDEX
            valueFrom:
              fieldRef:
                fieldPath: metadata.annotations['batch.kubernetes.io/job-completion-index']
          - name: MYFUNC
            value: |
              def reducer(entries):
                accumulator = dict()
                for key, value in entries.items():
                  if key in accumulator:
                    accumulator[key] += sum(value)
                  else:
                    accumulator[key] = sum(value)
                return accumulator
      restartPolicy: OnFailure
      volumes:
      - name: reducer-storage  # Fixed name here
        persistentVolumeClaim:
          claimName: keep-alive-pod-pvc
