apiVersion: v1
kind: Service
metadata:
  name: reducers
  labels:
    app: reducers
spec:
  ports:
    - port: 8080
      name: reducer
  clusterIP: None
  selector:
    app: reducers
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: reducer
spec:
  serviceName: "reducers"
  replicas: 1
  selector:
    matchLabels:
      app: reducers
  template:
    metadata:
      labels:
        app: reducers
    spec:
      containers:
        - name: mapreduce
          imagePullPolicy: IfNotPresent
          image: reducer:latest
          command: ["sh", "-c", "cp /mnt/data/reducer_input.py /reducer_input.py && python3 /reducer_skeleton.py -i /mnt/data/reducer/in/shuffler.out -o /mnt/data/reducer/out/reducer.out"]
          #command: ["python3"]
          #args: ["/reducer.py", "-i", "/mnt/data/reducer/in/shuffler.out", "-o", "/mnt/data/reducer/out/reducer.out"]
          ports:
            - containerPort: 8082
              name: reducer
          volumeMounts:
            - mountPath: "/mnt/data/"
              name: mapper-storage
      volumes:
      - name: mapper-storage
        persistentVolumeClaim:
          claimName: keep-alive-pod-pvc
