apiVersion: v1
kind: PersistentVolume
metadata:
  name: mapper-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keep-alive-pod-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: keep-alive-pod
spec:
  containers:
  - name: keep-alive-container
    image: busybox:1.32
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 3600; done"]
    resources:
      requests:
        cpu: "0.1"  # Request 0.1 CPU cores
        memory: "100Mi"  # Request 100 MiB memory
      limits:
        cpu: "0.5"  # Limit to 0.5 CPU cores
        memory: "500Mi"  # Limit to 500 MiB memory
    volumeMounts:
    - mountPath: "/mnt/data"
      name: mapper-storage
  volumes:
  - name: mapper-storage
    persistentVolumeClaim:
      claimName: keep-alive-pod-pvc
